### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by EnKrypt** [adithyakreddy/perfectly-timed#1]
[perfectly-timed](https://www.npmjs.com/package/perfectly-timed) is available on npmjs.org

Removes Git as a dependency and you don't have to clone and do `npm install`.

How to:
1. Maintain version number in package.json (subversion syntax)
2. Add shebang in entry point file. (#!/usr/bin/env node)
3. Add [`bin`](https://docs.npmjs.com/files/package.json#bin) entry in package.json
4. Run `npm publish` ( you may need to do `npm login`)

Optionally, add keywords in package.json to make it searchable.

**Comment by adithyakreddy** [comment]
Node.js and Git are required only for development. This wouldn't be appropriate as an npm package because it's meant to be a desktop application which you install and then launch, and you shouldn't need to have Node.js installed on your computer for it.

Once the app is in a runnable state we'll be packaging and distributing platform-specific binaries using [electron-builder](https://github.com/electron-userland/electron-builder) -- similar to [Visual Studio Code](https://code.visualstudio.com) and [Slack](https://slack.com/downloads/).

**Comment by EnKrypt** [comment]
Distribute where? Install from where?

Till you figure that out (and even after maybe), have npmjs be a medium.
